package com.example.wgwidget

object Sprites {

    val DINO_STAND = arrayOf(
        "..........XXXXXX.....",
        "..........XXXXXXXX...",
        "..........XXXXXXXX...",
        "..........XXXXXXXX...",
        "..........XXX.XXXX...",
        "..........XXXXXXXX...",
        "..........XX.........",
        "..........XXXX.......",
        ".X........XXXX.......",
        ".XX.......XXXXXX.....",
        ".XXX......XXXXXX.....",
        ".XXXXXXXXXXXXX.......",
        "..XXXXXXXXXXXX.......",
        "...XXXXXXXXX.........",
        "....XXXXXX...........",
        "....XXXXXX...........",
        "....XXXXXX...........",
        "....XX..XX...........",
        "....XX..XX...........",
        "....X....X...........",
        "....X....X...........",
    )

    val DINO_RUN1 = arrayOf(
        "..........XXXXXX.....",
        "..........XXXXXXXX...",
        "..........XXXXXXXX...",
        "..........XXXXXXXX...",
        "..........XXX.XXXX...",
        "..........XXXXXXXX...",
        "..........XX.........",
        "..........XXXX.......",
        ".X........XXXX.......",
        ".XX.......XXXXXX.....",
        ".XXX......XXXXXX.....",
        ".XXXXXXXXXXXXX.......",
        "..XXXXXXXXXXXX.......",
        "...XXXXXXXXX.........",
        "....XXXXXX...........",
        "....XXXXXX...........",
        "....XX..XX...........",
        "....X....X...........",
        "...XX....X...........",
        "...X......X..........",
        "..XX......X..........",
    )

    val DINO_RUN2 = arrayOf(
        "..........XXXXXX.....",
        "..........XXXXXXXX...",
        "..........XXXXXXXX...",
        "..........XXXXXXXX...",
        "..........XXX.XXXX...",
        "..........XXXXXXXX...",
        "..........XX.........",
        "..........XXXX.......",
        ".X........XXXX.......",
        ".XX.......XXXXXX.....",
        ".XXX......XXXXXX.....",
        ".XXXXXXXXXXXXX.......",
        "..XXXXXXXXXXXX.......",
        "...XXXXXXXXX.........",
        "....XXXXXX...........",
        "....XXXXXX...........",
        "....XX..XX...........",
        "....X....X...........",
        "....X....XX..........",
        "....X......X.........",
        "....X......XX........",
    )

    val DINO_DEAD = arrayOf(
        "..........XXXXXX.....",
        "..........XXXXXXXX...",
        "..........XXXXXXXX...",
        "..........XXXXXXXX...",
        "..........XXXXXXXX...",
        "..........XXXXXXXX...",
        "..........XX.........",
        "..........XXXX.......",
        ".X........XXXX.......",
        ".XX.......XXXXXX.....",
        ".XXX......XXXXXX.....",
        ".XXXXXXXXXXXXX.......",
        "..XXXXXXXXXXXX.......",
        "...XXXXXXXXX.........",
        "....XXXXXX...........",
        "....XXXXXX...........",
        "....XXXXXX...........",
        "....XX..XX...........",
        "....XX..XX...........",
        "....X....X...........",
        "....X....X...........",
    )

    val CACTUS_BIG = arrayOf(
        "..X..",
        "..X..",
        "X.X..",
        "X.X.X",
        "X.X.X",
        "XXXXX",
        "..X..",
        "..X..",
        "..X..",
    )
}
