package com.example.wgwidget

object Sprites {

    val DINO_STAND = arrayOf(
        "..............XXXXXX..",
        ".............XXXXXXXX.",
        ".............XXXXXXXX.",
        ".............XXXXXXXX.",
        ".............XXXX.XXX.",
        ".............XXXXXXXX.",
        ".............X........",
        ".............XXXX.....",
        ".............XXXX.....",
        "X............XXXXXX...",
        "XX...........XXXXXX...",
        "XXX..........XXXXXX...",
        "XXXXX........XXXXX....",
        ".XXXXXXXXXXXXXXXX.....",
        "..XXXXXXXXXXXXXX......",
        "...XXXXXXXXXXXX.......",
        "....XXXXXXXXX.........",
        ".....XXXXXXX..........",
        "......XXXXX...........",
        ".....XX..XX...........",
        ".....XX..XX...........",
        "......X....X..........",
    )

    val DINO_RUN1 = arrayOf(
        "..............XXXXXX..",
        ".............XXXXXXXX.",
        ".............XXXXXXXX.",
        ".............XXXXXXXX.",
        ".............XXXX.XXX.",
        ".............XXXXXXXX.",
        ".............X........",
        ".............XXXX.....",
        ".............XXXX.....",
        "X............XXXXXX...",
        "XX...........XXXXXX...",
        "XXX..........XXXXXX...",
        "XXXXX........XXXXX....",
        ".XXXXXXXXXXXXXXXX.....",
        "..XXXXXXXXXXXXXX......",
        "...XXXXXXXXXXXX.......",
        "....XXXXXXXXX.........",
        ".....XXXXXXX..........",
        "......XXXXX...........",
        ".....X...XX...........",
        ".....X...X............",
        ".....XXX..X...........",
    )

    val DINO_RUN2 = arrayOf(
        "..............XXXXXX..",
        ".............XXXXXXXX.",
        ".............XXXXXXXX.",
        ".............XXXXXXXX.",
        ".............XXXX.XXX.",
        ".............XXXXXXXX.",
        ".............X........",
        ".............XXXX.....",
        ".............XXXX.....",
        "X............XXXXXX...",
        "XX...........XXXXXX...",
        "XXX..........XXXXXX...",
        "XXXXX........XXXXX....",
        ".XXXXXXXXXXXXXXXX.....",
        "..XXXXXXXXXXXXXX......",
        "...XXXXXXXXXXXX.......",
        "....XXXXXXXXX.........",
        ".....XXXXXXX..........",
        "......XXXXX...........",
        ".....XX...X...........",
        "......X...X...........",
        "......X..XXX..........",
    )

    val DINO_DEAD = arrayOf(
        "..............XXXXXX..",
        ".............XXXXXXXX.",
        ".............XXXXXXXX.",
        ".............XXXXXXXX.",
        ".............XXXXXXXX.",
        ".............XXXXXXXX.",
        ".............X........",
        ".............XXXX.....",
        ".............XXXX.....",
        "X............XXXXXX...",
        "XX...........XXXXXX...",
        "XXX..........XXXXXX...",
        "XXXXX........XXXXX....",
        ".XXXXXXXXXXXXXXXX.....",
        "..XXXXXXXXXXXXXX......",
        "...XXXXXXXXXXXX.......",
        "....XXXXXXXXX.........",
        ".....XXXXXXX..........",
        "......XXXXX...........",
        ".....XX..XX...........",
        ".....XX..XX...........",
        "......X....X..........",
    )

    val CACTUS_BIG = arrayOf(
        "..X..",
        "..X..",
        "X.X..",
        "X.X.X",
        "X.X.X",
        "XXXXX",
        "..X..",
        "..X..",
        "..X..",
    )
}
